### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by twoletters** [brndnmtthws/optimal-buy-cbpro#27]
The Dockerfile reads from missing file `requirements.txt`. It was in the initial commit but was removed later on.

It'd be great to add instructions on how to build the docker. The `systemd` files also rely on Docker and it'd be useful to provide non-docker versions of these files.

**Comment by brndnmtthws** [comment]
From the source dir, you can run `pip install .` to install everything.

It looks like I broke the Docker build at some point, which is my bad.

The image will be available here (after I fix it): https://hub.docker.com/r/brndnmtthws/optimal-buy-cbpro

Old builds are also available here: https://hub.docker.com/r/brndnmtthws/optimal-buy-gdax

**Comment by brndnmtthws** [comment]
This should be fixed now with a3682f.
