### ISSUE TITLE
working example of coins json string

### ISSUE THREAD

**Issue by devbhosale** [brndnmtthws/optimal-buy-cbpro#31]
Do you have any working examples of coins parameter in a JSON string..

I tried things following variations but all of them threw some kind of error.

The following threw "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"

--coins='{"BTC":{"name":"Bitcoin","withdrawal_address":null,"external_balance":0},"ETH":{"name":"Ethereum","withdrawal_address":null,"external_balance":0},"LTC":{"name":"Litecoin","withdrawal_address":null,"external_balance":0}}'

and the this one threw "TypeError: string indices must be integers"
 """{"BTC":{"name":"Bitcoin","withdrawal_address":null,"external_balance":0},"ETH":{"name":"Ethereum","withdrawal_address":null,"external_balance":0},"LTC":{"name":"Litecoin","withdrawal_address":null,"external_balance":0}}"""

**Comment by brndnmtthws** [comment]
Try removing the equal sign (`=`). Like this:

```
--coins '{"BTC":{"name":"Bitcoin","withdrawal_address":null,"external_balance":0},"ETH":{"name":"Ethereum","withdrawal_address":null,"external_balance":0},"LTC":{"name":"Litecoin","withdrawal_address":null,"external_balance":0}}'
```
